In [35]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np
from IPython.core.pylabtools import figsize
pd.options.display.float_format = '{:,.6f}'.format
np.set_printoptions(precision=15,suppress=True)

In [4]:
columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
df = pd.read_csv('../data/housing.data', header=None, names=columns, sep='\s+')

In [30]:
# Feature Normalization
def normalize(x):
    max_val = max(x)
    min_val = min(x)
    avg = np.mean(x)
    normalized = [(i-avg)/(max_val - min_val) for i in x]
    return normalized

In [39]:
df = df.apply(normalize,axis=0)
# Create X0 column
Xd = df.drop(columns=['MEDV'])
X = Xd.values
m = len(Xd.index)
y = df.MEDV.to_numpy().reshape(m,1)

In [40]:
lg = LinearRegression()
lg.fit(X,y)
print(f"Intercept : {lg.intercept_}, Thetas : {lg.coef_}")

Intercept : [-0.], Thetas : [[-0.213550167675041  0.103156574148625  0.012463096162082
   0.059705195985442 -0.191879401265641  0.441859700318606
   0.001493666946166 -0.36059246765292   0.156425289259088
  -0.143629493606333 -0.199018310623301  0.08206283006047
  -0.422605413632954]]


In [19]:
h = lg.predict(df1).reshape(len(df1),1)
y = df.MEDV.to_numpy().reshape(len(df1),1)
np.hstack([y,h])

array([[24.        , 30.00384338],
       [21.6       , 25.02556238],
       [34.7       , 30.56759672],
       ...,
       [23.9       , 27.6274261 ],
       [22.        , 26.12796681],
       [11.9       , 22.34421229]])

In [41]:
h = lg.predict(X).reshape(len(X),1)
np.hstack([y,h])

array([[ 0.032604303908652,  0.166023045620136],
       [-0.020729029424682,  0.055394578998722],
       [ 0.27038208168643 ,  0.178550897655354],
       ...,
       [ 0.030382081686429,  0.113213772687227],
       [-0.011840140535793,  0.079892455166336],
       [-0.236284584980237, -0.004190978471268]])

In [42]:
X

array([[-0.040544098264629,  0.066363636363636, -0.323562267453317, ...,
        -0.335695063493398,  0.10143216596764 , -0.211729118132084],
       [-0.040308175725451, -0.113636363636364, -0.149075463934255, ...,
        -0.069737616684888,  0.10143216596764 , -0.096938831156366],
       [-0.040308400520628, -0.113636363636364, -0.149075463934255, ...,
        -0.069737616684888,  0.091169419485215, -0.237943246167404],
       ...,
       [-0.039932205790457, -0.113636363636364,  0.029077028734366, ...,
         0.270687915230006,  0.10143216596764 , -0.193517197602283],
       [-0.039383368363678, -0.113636363636364,  0.029077028734366, ...,
         0.270687915230006,  0.092732786271236, -0.170338389655263],
       [-0.040082256571688, -0.113636363636364,  0.029077028734366, ...,
         0.270687915230006,  0.10143216596764 , -0.131707043076896]])